//
// PaymentReferences.swift
// VoltCheckout
//
// Created by Maciej Sienkiewicz on 15/10/2025.
// Copyright © 2025 Volt Technologies Holdings Ltd. All rights reserved.
//

import Foundation

/// References that can be associated with a payment to further identify it across various systems.
public struct PaymentReferences: Hashable, Equatable, Codable, Sendable {
    /// Unique reference for the payment from the partner's system.
    /// Reference can contain only up to 18 alphanumeric characters.
    /// If this value is not provided, it will be generated by Volt, and returned with payment status.
    public let paymentReference: String?

    /// Identifier of the transaction in the partner's system.
    /// This field can contain up to 100 characters, including special ones.
    public let internalReference: String?
    
    /// Performs validation of provided properties, and returns `nil` when any is not valid.
    /// - Parameters:
    ///   - paymentReference: Payment reference.
    ///   - internalReference: Internal reference.
    public init?(paymentReference: String? = nil, internalReference: String? = nil) {
        if let pRef = paymentReference {
            guard pRef.count <= 18, pRef.rangeOfCharacter(from: .alphanumerics.inverted) == nil else { return nil }
        }
        if let iRef = internalReference {
            guard iRef.count <= 100 else { return nil }
        }

        self.paymentReference = paymentReference
        self.internalReference = internalReference
    }
}
